# Remap prefix to <C-a>
unbind C-b
set -g prefix C-a

# General
set -g default-shell /bin/zsh # Use zsh as default shell
set -g set-clipboard on # Use system clipboard
set -g history-limit 100000 # Increase history size
set -g mouse on # Enable mouse support
set -g status-interval 3 # Update the status bar every 3 seconds
set -g default-terminal "tmux-256color" # Enable 256-Color support
set -ga terminal-overrides ",*256col*:Tc" # Enable true color support

# Appearance
c_text="#CAD3F5"
c_subtext="#5B6078"
c_mauve="#C6A0F6"
c_surface="#5B6078"
c_rosewater="#F4DBD6"
set -g status-position top # Display the status bar at the top of the screen
set -g status-left-length 48 # Allow 48 characters to displayed
set -g status-style "bg=default,fg=${c_text}"
set -g status-left "#[fg=${c_mauve},bold] #S #[fg=${c_surface},nobold]| "
set -g status-right ""
set -g window-status-current-format "#[fg=${c_rosewater}] #[underscore]#I:#W"
set -g window-status-format "#[fg=${c_subtext}]#I:#W"

# Keybinds
bind r source-file ~/.config/tmux/tmux.conf # Reload the tmux config

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

set -g @continuum-boot on
set -g @continuum-boot-options "ghostty"

# Initialize TPM
run ~/.config/tmux/plugins/tpm/tpm
